# coding: utf-8

"""
    @weka-api

    <div>The Weka system supports a RESTful API. This is useful when automating the interaction with the Weka system and when integrating it into your workflows or monitoring systems. The API is accessible at port 14000, via the /api/v2 URL, you can explore it via /api/v2/docs when accessing from the cluster (e.g. https://weka01:14000/api/v2/docs).<div style=\"margin-top: 15px;\">Note: Weka uses 64bit numbers. Please take special care when interacting with the API with different program languages (In JS for example you can use \"json-bigint\")</div></div>  # noqa: E501

    OpenAPI spec version: 3.12.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.kms_api import KMSApi  # noqa: E501
from swagger_client.rest import ApiException


class TestKMSApi(unittest.TestCase):
    """KMSApi unit test stubs"""

    def setUp(self):
        self.api = KMSApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_kms(self):
        """Test case for delete_kms

        Delete kms configuration  # noqa: E501
        """
        pass

    def test_get_kms(self):
        """Test case for get_kms

        Get kms configuration  # noqa: E501
        """
        pass

    def test_get_kms_type(self):
        """Test case for get_kms_type

        Get kms type  # noqa: E501
        """
        pass

    def test_rewrap_kms_key(self):
        """Test case for rewrap_kms_key

        Rewrap KMS key  # noqa: E501
        """
        pass

    def test_set_kms(self):
        """Test case for set_kms

        Set kms vault configuration (base_url,master_key_name,token) or set kms kmip configuration (server_endpoint, key_uid, client_cert_pem, client_key_pem, ca_cert_pem)   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
