# coding: utf-8

"""
    @weka-api

    <div>The Weka system supports a RESTful API. This is useful when automating the interaction with the Weka system and when integrating it into your workflows or monitoring systems. The API is accessible at port 14000, via the /api/v2 URL, you can explore it via /api/v2/docs when accessing from the cluster (e.g. https://weka01:14000/api/v2/docs).<div style=\"margin-top: 15px;\">Note: Weka uses 64bit numbers. Please take special care when interacting with the API with different program languages (In JS for example you can use \"json-bigint\")</div></div>  # noqa: E501

    OpenAPI spec version: 3.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.weka_home_api import WekaHomeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWekaHomeApi(unittest.TestCase):
    """WekaHomeApi unit test stubs"""

    def setUp(self):
        self.api = WekaHomeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_disable_cloud(self):
        """Test case for disable_cloud

        Disable cloud  # noqa: E501
        """
        pass

    def test_enable_cloud(self):
        """Test case for enable_cloud

        Enable cloud  # noqa: E501
        """
        pass

    def test_get_cloud(self):
        """Test case for get_cloud

        Get cloud config  # noqa: E501
        """
        pass

    def test_get_cloud_proxy(self):
        """Test case for get_cloud_proxy

        Get cloud proxy  # noqa: E501
        """
        pass

    def test_get_cloud_upload_rate(self):
        """Test case for get_cloud_upload_rate

        Get cloud upload rate  # noqa: E501
        """
        pass

    def test_get_cloud_url(self):
        """Test case for get_cloud_url

        Get cloud url  # noqa: E501
        """
        pass

    def test_set_cloud_proxy(self):
        """Test case for set_cloud_proxy

        Set cloud proxy  # noqa: E501
        """
        pass

    def test_update_cloud_upload_rate(self):
        """Test case for update_cloud_upload_rate

        Update cloud upload rate  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
