# coding: utf-8

"""
    @weka-api

    <div>The Weka system supports a RESTful API. This is useful when automating the interaction with the Weka system and when integrating it into your workflows or monitoring systems. The API is accessible at port 14000, via the /api/v2 URL, you can explore it via /api/v2/docs when accessing from the cluster (e.g. https://weka01:14000/api/v2/docs).<div style=\"margin-top: 15px;\">Note: Weka uses 64bit numbers. Please take special care when interacting with the API with different program languages (In JS for example you can use \"json-bigint\")</div></div>  # noqa: E501

    OpenAPI spec version: 3.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20081Params(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'obs_id': 'str',
        'fs_id': 'str',
        'purpose': 'str'
    }

    attribute_map = {
        'obs_id': 'obsId',
        'fs_id': 'fsId',
        'purpose': 'purpose'
    }

    def __init__(self, obs_id=None, fs_id=None, purpose=None):  # noqa: E501
        """InlineResponse20081Params - a model defined in Swagger"""  # noqa: E501
        self._obs_id = None
        self._fs_id = None
        self._purpose = None
        self.discriminator = None
        if obs_id is not None:
            self.obs_id = obs_id
        if fs_id is not None:
            self.fs_id = fs_id
        if purpose is not None:
            self.purpose = purpose

    @property
    def obs_id(self):
        """Gets the obs_id of this InlineResponse20081Params.  # noqa: E501


        :return: The obs_id of this InlineResponse20081Params.  # noqa: E501
        :rtype: str
        """
        return self._obs_id

    @obs_id.setter
    def obs_id(self, obs_id):
        """Sets the obs_id of this InlineResponse20081Params.


        :param obs_id: The obs_id of this InlineResponse20081Params.  # noqa: E501
        :type: str
        """

        self._obs_id = obs_id

    @property
    def fs_id(self):
        """Gets the fs_id of this InlineResponse20081Params.  # noqa: E501


        :return: The fs_id of this InlineResponse20081Params.  # noqa: E501
        :rtype: str
        """
        return self._fs_id

    @fs_id.setter
    def fs_id(self, fs_id):
        """Sets the fs_id of this InlineResponse20081Params.


        :param fs_id: The fs_id of this InlineResponse20081Params.  # noqa: E501
        :type: str
        """

        self._fs_id = fs_id

    @property
    def purpose(self):
        """Gets the purpose of this InlineResponse20081Params.  # noqa: E501


        :return: The purpose of this InlineResponse20081Params.  # noqa: E501
        :rtype: str
        """
        return self._purpose

    @purpose.setter
    def purpose(self, purpose):
        """Sets the purpose of this InlineResponse20081Params.


        :param purpose: The purpose of this InlineResponse20081Params.  # noqa: E501
        :type: str
        """

        self._purpose = purpose

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20081Params, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20081Params):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
