# coding: utf-8

"""
    @weka-api

    <div>The Weka system supports a RESTful API. This is useful when automating the interaction with the Weka system and when integrating it into your workflows or monitoring systems. The API is accessible at port 14000, via the /api/v2 URL, you can explore it via /api/v2/docs when accessing from the cluster (e.g. https://weka01:14000/api/v2/docs).<div style=\"margin-top: 15px;\">Note: Weka uses 64bit numbers. Please take special care when interacting with the API with different program languages (In JS for example you can use \"json-bigint\")</div></div>  # noqa: E501

    OpenAPI spec version: 3.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FailureDomain(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'uid': 'str',
        'drives': 'list[str]',
        'hosts': 'list[str]'
    }

    attribute_map = {
        'id': 'id',
        'uid': 'uid',
        'drives': 'drives',
        'hosts': 'hosts'
    }

    def __init__(self, id=None, uid=None, drives=None, hosts=None):  # noqa: E501
        """FailureDomain - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._uid = None
        self._drives = None
        self._hosts = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if uid is not None:
            self.uid = uid
        if drives is not None:
            self.drives = drives
        if hosts is not None:
            self.hosts = hosts

    @property
    def id(self):
        """Gets the id of this FailureDomain.  # noqa: E501


        :return: The id of this FailureDomain.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FailureDomain.


        :param id: The id of this FailureDomain.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def uid(self):
        """Gets the uid of this FailureDomain.  # noqa: E501


        :return: The uid of this FailureDomain.  # noqa: E501
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid):
        """Sets the uid of this FailureDomain.


        :param uid: The uid of this FailureDomain.  # noqa: E501
        :type: str
        """

        self._uid = uid

    @property
    def drives(self):
        """Gets the drives of this FailureDomain.  # noqa: E501


        :return: The drives of this FailureDomain.  # noqa: E501
        :rtype: list[str]
        """
        return self._drives

    @drives.setter
    def drives(self, drives):
        """Sets the drives of this FailureDomain.


        :param drives: The drives of this FailureDomain.  # noqa: E501
        :type: list[str]
        """

        self._drives = drives

    @property
    def hosts(self):
        """Gets the hosts of this FailureDomain.  # noqa: E501


        :return: The hosts of this FailureDomain.  # noqa: E501
        :rtype: list[str]
        """
        return self._hosts

    @hosts.setter
    def hosts(self, hosts):
        """Sets the hosts of this FailureDomain.


        :param hosts: The hosts of this FailureDomain.  # noqa: E501
        :type: list[str]
        """

        self._hosts = hosts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FailureDomain, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FailureDomain):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
