# coding: utf-8

"""
    @weka-api

    <div>The Weka system supports a RESTful API. This is useful when automating the interaction with the Weka system and when integrating it into your workflows or monitoring systems. The API is accessible at port 14000, via the /api/v2 URL, you can explore it via /api/v2/docs when accessing from the cluster (e.g. https://weka01:14000/api/v2/docs).<div style=\"margin-top: 15px;\">Note: Weka uses 64bit numbers. Please take special care when interacting with the API with different program languages (In JS for example you can use \"json-bigint\")</div></div>  # noqa: E501

    OpenAPI spec version: 3.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InterfaceGroupsUidBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'gateway': 'str',
        'subnet': 'str'
    }

    attribute_map = {
        'gateway': 'gateway',
        'subnet': 'subnet'
    }

    def __init__(self, gateway=None, subnet=None):  # noqa: E501
        """InterfaceGroupsUidBody - a model defined in Swagger"""  # noqa: E501
        self._gateway = None
        self._subnet = None
        self.discriminator = None
        if gateway is not None:
            self.gateway = gateway
        if subnet is not None:
            self.subnet = subnet

    @property
    def gateway(self):
        """Gets the gateway of this InterfaceGroupsUidBody.  # noqa: E501

        Gateway ip  # noqa: E501

        :return: The gateway of this InterfaceGroupsUidBody.  # noqa: E501
        :rtype: str
        """
        return self._gateway

    @gateway.setter
    def gateway(self, gateway):
        """Sets the gateway of this InterfaceGroupsUidBody.

        Gateway ip  # noqa: E501

        :param gateway: The gateway of this InterfaceGroupsUidBody.  # noqa: E501
        :type: str
        """

        self._gateway = gateway

    @property
    def subnet(self):
        """Gets the subnet of this InterfaceGroupsUidBody.  # noqa: E501

        Subnet mask in the 255.255.0.0 format  # noqa: E501

        :return: The subnet of this InterfaceGroupsUidBody.  # noqa: E501
        :rtype: str
        """
        return self._subnet

    @subnet.setter
    def subnet(self, subnet):
        """Sets the subnet of this InterfaceGroupsUidBody.

        Subnet mask in the 255.255.0.0 format  # noqa: E501

        :param subnet: The subnet of this InterfaceGroupsUidBody.  # noqa: E501
        :type: str
        """

        self._subnet = subnet

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InterfaceGroupsUidBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InterfaceGroupsUidBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
