# coding: utf-8

"""
    @weka-api

    <div>The Weka system supports a RESTful API. This is useful when automating the interaction with the Weka system and when integrating it into your workflows or monitoring systems. The API is accessible at port 14000, via the /api/v2 URL, you can explore it via /api/v2/docs when accessing from the cluster (e.g. https://weka01:14000/api/v2/docs).<div style=\"margin-top: 15px;\">Note: Weka uses 64bit numbers. Please take special care when interacting with the API with different program languages (In JS for example you can use \"json-bigint\")</div></div>  # noqa: E501

    OpenAPI spec version: 3.14
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InterfaceGroupsPortBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'host_uid': 'str',
        'port': 'str',
        'uid': 'str'
    }

    attribute_map = {
        'host_uid': 'host_uid',
        'port': 'port',
        'uid': 'uid'
    }

    def __init__(self, host_uid=None, port=None, uid=None):  # noqa: E501
        """InterfaceGroupsPortBody - a model defined in Swagger"""  # noqa: E501
        self._host_uid = None
        self._port = None
        self._uid = None
        self.discriminator = None
        self.host_uid = host_uid
        self.port = port
        self.uid = uid

    @property
    def host_uid(self):
        """Gets the host_uid of this InterfaceGroupsPortBody.  # noqa: E501

        Host UUID  # noqa: E501

        :return: The host_uid of this InterfaceGroupsPortBody.  # noqa: E501
        :rtype: str
        """
        return self._host_uid

    @host_uid.setter
    def host_uid(self, host_uid):
        """Sets the host_uid of this InterfaceGroupsPortBody.

        Host UUID  # noqa: E501

        :param host_uid: The host_uid of this InterfaceGroupsPortBody.  # noqa: E501
        :type: str
        """
        if host_uid is None:
            raise ValueError("Invalid value for `host_uid`, must not be `None`")  # noqa: E501

        self._host_uid = host_uid

    @property
    def port(self):
        """Gets the port of this InterfaceGroupsPortBody.  # noqa: E501


        :return: The port of this InterfaceGroupsPortBody.  # noqa: E501
        :rtype: str
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this InterfaceGroupsPortBody.


        :param port: The port of this InterfaceGroupsPortBody.  # noqa: E501
        :type: str
        """
        if port is None:
            raise ValueError("Invalid value for `port`, must not be `None`")  # noqa: E501

        self._port = port

    @property
    def uid(self):
        """Gets the uid of this InterfaceGroupsPortBody.  # noqa: E501

        Interface Group UUID  # noqa: E501

        :return: The uid of this InterfaceGroupsPortBody.  # noqa: E501
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid):
        """Sets the uid of this InterfaceGroupsPortBody.

        Interface Group UUID  # noqa: E501

        :param uid: The uid of this InterfaceGroupsPortBody.  # noqa: E501
        :type: str
        """
        if uid is None:
            raise ValueError("Invalid value for `uid`, must not be `None`")  # noqa: E501

        self._uid = uid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InterfaceGroupsPortBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InterfaceGroupsPortBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
